/*PROJETO PARA RADIO */

/* CRIANDO TABELAS */

/* TABELA ARTISTAS */

CREATE TABLE ARTISTAS(
    idARTISTA INT PRIMARY KEY IDENTITY(1,1),
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(1) NOT NULL
	CHECK(SEXO IN('F','M')),
	DATA_DE_NASCIMENTO DATE NOT NULL,
	id_PAIS INT NOT NULL,
	id_GRAVADORA INT NOT NULL 
);
GO

/* TABELA PAISES */

CREATE TABLE PAISES(
    idPAIS INT PRIMARY KEY IDENTITY(1,1),
	NOME VARCHAR(30) NOT NULL,
	LINGUA_OFICIAL VARCHAR(30) NOT NULL,
	CONTINENTE VARCHAR(30) NOT NULL,
);
GO

/* TABELA GRAVADORAS/ ENDERECO GRAVADORA / TELEFONE GRAVADORA */

CREATE TABLE GRAVADORAS(
     idGRAVADORA INT PRIMARY KEY IDENTITY(1,1),
	 NOME VARCHAR(30) NOT NULL UNIQUE,
	 NOME_DIRETOR VARCHAR(30) NOT NULL,
);
GO

CREATE TABLE ENDERECOS(
     idENDERECO INT PRIMARY KEY IDENTITY(1,1),
	 RUA VARCHAR(30) NOT NULL,
	 BAIRRO VARCHAR(30) NOT NULL,
	 CIDADE VARCHAR(30) NOT NULL,
	 UF CHAR(2) NOT NULL,
	 id_GRAVADORA INT UNIQUE
);
GO

CREATE TABLE TELEFONES(
     idTELEFONE INT PRIMARY KEY IDENTITY(1,1),
	 TIPO CHAR(3) NOT NULL,
	 NUMERO VARCHAR(30) NOT NULL,
	 id_GRAVADORA INT,
);
GO

/* CRIANDO TABELA ALBUNS */

CREATE TABLE ALBUNS(
     idALBUM INT PRIMARY KEY IDENTITY(1,1),
	 NOME VARCHAR(30) NOT NULL,
	 ESTILO VARCHAR(30) NOT NULL,
	 DATA_LANCAMENTO DATE,
	 id_GRAVADORA INT
);
GO

/* CRIANDO TABELA MUSICAS */

CREATE TABLE MUSICAS(
     idMUSICA INT PRIMARY KEY IDENTITY(1,1),
	 NOME VARCHAR(30) NOT NULL,
	 TEMPO_DURACAO VARCHAR(30) NOT NULL,
	 id_ALBUM INT
);
GO

/* CRIANDO TABELA ASSOCIATIVA ARTISTAS_MUSICAS */

CREATE TABLE ARTISTAS_MUSICAS(
     id_MUSICA INT NOT NULL,
	 id_ARTISTA INT NOT NULL
);
GO

/* CRIANDO AS CONSTRAINTS */

USE RADIO;
GO

/* ARTISTAS X PAISES */

ALTER TABLE ARTISTAS ADD CONSTRAINT FK_ARTISTAS_PAISES
FOREIGN KEY(id_PAIS) REFERENCES PAISES(idPAIS);
GO

/* ARTISTAS X GRAVADORAS */

ALTER TABLE ARTISTAS ADD CONSTRAINT FK_ARTISTAS_GRAVADORAS
FOREIGN KEY(id_GRAVADORA) REFERENCES GRAVADORAS(idGRAVADORA);
GO

/* ALBUNS X GRAVADORAS */

ALTER TABLE ALBUNS ADD CONSTRAINT FK_ALBUNS_GRAVADORAS
FOREIGN KEY(id_GRAVADORA) REFERENCES GRAVADORAS(idGRAVADORA);
GO

/* ALBUNS X MUSICAS */

ALTER TABLE MUSICAS ADD CONSTRAINT FK_MUSICAS_ALBUNS
FOREIGN KEY(id_ALBUM) REFERENCES ALBUNS(idALBUM);
GO

/* ARTISTAS X MUSICAS */

ALTER TABLE ARTISTAS_MUSICAS ADD CONSTRAINT PK_ARTISTAS_MUSICAS
PRIMARY KEY(id_MUSICA,id_ARTISTA);
GO

ALTER TABLE ARTISTAS_MUSICAS ADD CONSTRAINT FK_ARTISTAS_MUSICAS
FOREIGN KEY(id_MUSICA) REFERENCES MUSICAS(idMUSICA);
GO

ALTER TABLE ARTISTAS_MUSICAS ADD CONSTRAINT FK_ARTISTAS_ARTISTAS
FOREIGN KEY(id_ARTISTA) REFERENCES ARTISTAS(idARTISTA);
GO


/* INSERTS */

/* INSERINDO NA TABELA PAÍSES */

INSERT INTO PAISES VALUES('Brasil','Brasileiro','America do Sul');
GO

INSERT INTO PAISES VALUES('Estados Unidos', 'Americano', 'América do Norte');
GO

INSERT INTO PAISES VALUES('Reino Unido', 'Britânico', 'Europa');
GO

/* INSERINDO NA TABELA GRAVADORAS*/

INSERT INTO GRAVADORAS VALUES('Warner Music Brasil','Leila Oliveira');
GO

INSERT INTO GRAVADORAS VALUES('Sony Music', 'Rob Stringer');
GO

INSERT INTO GRAVADORAS VALUES('Universal Music Group', 'Lucian Grainge');
GO

INSERT INTO GRAVADORAS VALUES('30PRAUM', 'Matuê');
GO

INSERT INTO GRAVADORAS VALUES('Cactus Jack Records', 'Travis Scott');
GO

/* INSERINDO NA TABELA ARTISTAS */

INSERT INTO ARTISTAS VALUES('Kayblack','M','2000-03-12',1,1);
GO

INSERT INTO ARTISTAS VALUES('Taylor Swift', 'F', '1989-12-13', 2, 2);
GO

INSERT INTO ARTISTAS VALUES('Ed Sheeran', 'M', '1991-02-17', 3, 3);
GO

INSERT INTO ARTISTAS VALUES('Matuê', 'M', '1993-10-11', 1, 4);
GO

INSERT INTO ARTISTAS VALUES('Travis Scott','M','1991-04-30',2,5);
GO

/* INSERINDO NA TABELA ALBUNS */

INSERT INTO ALBUNS VALUES('Constradições','Trap','2023-03-31',1);
GO

INSERT INTO ALBUNS VALUES('1989', 'Pop', '2014-10-27', 2);
GO

INSERT INTO ALBUNS VALUES('÷ (Divide)', 'Pop', '2017-03-03', 3);
GO

INSERT INTO ALBUNS VALUES('Máquina do Tempo', 'Trap', '2020-09-10', 4);
GO

INSERT INTO ALBUNS VALUES('Astroworld','Hip Hop','2018-08-03',5);
GO

/* INSERINDO NA TABELA MUSICAS */

INSERT INTO MUSICAS VALUES('Desejos','2:08',1);
GO

INSERT INTO MUSICAS VALUES('Shake It Off', '3:39', 2);
GO

INSERT INTO MUSICAS VALUES('Perfect', '4:23', 3);
GO

INSERT INTO MUSICAS VALUES('Máquina do Tempo', '2:52', 4);
INSERT INTO MUSICAS VALUES('Quer Voar', '2:40', 4);
INSERT INTO MUSICAS VALUES('Cogulândia', '2:31', 4);
INSERT INTO MUSICAS VALUES('É Sal', '2:24', 4);
INSERT INTO MUSICAS VALUES('Banco', '2:56', 4);
INSERT INTO MUSICAS VALUES('Anos Luz', '2:39', 4);
INSERT INTO MUSICAS VALUES('Kenny G', '3:05', 4);
GO

INSERT INTO MUSICAS VALUES('Stargazing','4:30',5);
INSERT INTO MUSICAS VALUES('Carousel', '3:00', 5);
INSERT INTO MUSICAS VALUES('Sicko Mode', '5:12', 5);
INSERT INTO MUSICAS VALUES('R.I.P. Screw', '3:05', 5);
INSERT INTO MUSICAS VALUES('Stop Trying to Be God', '5:38', 5);
INSERT INTO MUSICAS VALUES('No Bystanders', '3:38', 5);
INSERT INTO MUSICAS VALUES('Skeletons', '2:25', 5);
INSERT INTO MUSICAS VALUES('Wake Up', '3:52', 5);
INSERT INTO MUSICAS VALUES('5% Tint', '3:16', 5);
INSERT INTO MUSICAS VALUES('NC-17', '2:37', 5);
INSERT INTO MUSICAS VALUES('Astrothunder', '2:23', 5);
INSERT INTO MUSICAS VALUES('Yosemite', '2:30', 5);
INSERT INTO MUSICAS VALUES('Can’t Say', '3:18', 5);
INSERT INTO MUSICAS VALUES('Who? What!', '2:57', 5);
INSERT INTO MUSICAS VALUES('Butterfly Effect', '3:10', 5);
INSERT INTO MUSICAS VALUES('Houstonfornication', '3:38', 5);
INSERT INTO MUSICAS VALUES('Coffee Bean', '3:29', 5);
GO


/* INSERINDO NA TABELA MUSICAS_ARTISTAS */

INSERT INTO ARTISTAS_MUSICAS VALUES(1,1);
GO
INSERT INTO ARTISTAS_MUSICAS VALUES(2, 1);
GO
INSERT INTO ARTISTAS_MUSICAS VALUES(3, 2);
GO
INSERT INTO ARTISTAS_MUSICAS VALUES(4, 1);
GO
INSERT INTO ARTISTAS_MUSICAS VALUES(22, 4);
GO
INSERT INTO ARTISTAS_MUSICAS VALUES(23, 4);
GO
INSERT INTO ARTISTAS_MUSICAS VALUES(24, 4);
GO
INSERT INTO ARTISTAS_MUSICAS VALUES(25, 4);
GO
INSERT INTO ARTISTAS_MUSICAS VALUES(26, 4);
GO
INSERT INTO ARTISTAS_MUSICAS VALUES(27, 4);
GO
INSERT INTO ARTISTAS_MUSICAS VALUES(5, 1);
GO
INSERT INTO ARTISTAS_MUSICAS VALUES(5, 5);
GO
INSERT INTO ARTISTAS_MUSICAS VALUES(6, 5);
GO
INSERT INTO ARTISTAS_MUSICAS VALUES(7, 5);
GO
INSERT INTO ARTISTAS_MUSICAS VALUES(8, 5);
GO
INSERT INTO ARTISTAS_MUSICAS VALUES(9, 5);
GO
INSERT INTO ARTISTAS_MUSICAS VALUES(10, 5);
GO
INSERT INTO ARTISTAS_MUSICAS VALUES(11, 5);
GO
INSERT INTO ARTISTAS_MUSICAS VALUES(12, 5);
GO
INSERT INTO ARTISTAS_MUSICAS VALUES(13, 5);
GO
INSERT INTO ARTISTAS_MUSICAS VALUES(14, 5);
GO
INSERT INTO ARTISTAS_MUSICAS VALUES(15, 5);
GO
INSERT INTO ARTISTAS_MUSICAS VALUES(16, 5);
GO
INSERT INTO ARTISTAS_MUSICAS VALUES(17, 5);
GO
INSERT INTO ARTISTAS_MUSICAS VALUES(18, 5);
GO
INSERT INTO ARTISTAS_MUSICAS VALUES(19, 5);
GO
INSERT INTO ARTISTAS_MUSICAS VALUES(20, 5);
GO
INSERT INTO ARTISTAS_MUSICAS VALUES(21, 5);
GO


sp_columns artistas_musicas;

SELECT M.NOME AS "Musica",
       A.NOME AS "Album",
	   AR.NOME AS "Cantor",
	   P.NOME AS "Pais do Artista",
	   G.NOME AS "Gravadora"
FROM GRAVADORAS G
	INNER JOIN ARTISTAS AR
	ON AR.id_GRAVADORA = G.idGRAVADORA
	INNER JOIN ALBUNS A
	ON A.id_GRAVADORA = G.idGRAVADORA
	INNER JOIN MUSICAS M
	ON M.id_ALBUM = A.idALBUM
	INNER JOIN PAISES P
	ON AR.id_PAIS = P.idPAIS;
GO

CREATE VIEW DADOS_MUSICA AS
SELECT M.NOME AS "Musica",
       A.NOME AS "Album",
	   AR.NOME AS "Cantor",
	   P.NOME AS "Pais do Artista",
	   G.NOME AS "Gravadora"
FROM GRAVADORAS G
	INNER JOIN ARTISTAS AR
	ON AR.id_GRAVADORA = G.idGRAVADORA
	INNER JOIN ALBUNS A
	ON A.id_GRAVADORA = G.idGRAVADORA
	INNER JOIN MUSICAS M
	ON M.id_ALBUM = A.idALBUM
	INNER JOIN PAISES P
	ON AR.id_PAIS = P.idPAIS;
GO

SELECT * FROM DADOS_MUSICA;

/* ALGUMAS CONSULTAS POSSÍVEIS PARA ESTÉ BANCO */

/* Listar todas as músicas de um determinado álbum */

SELECT NOME AS "Musicas"
FROM MUSICAS
WHERE id_ALBUM = (SELECT idALBUM FROM ALBUNS WHERE NOME = 'Astroworld');
GO

/* Encontrar todos os álbuns de um determinado estilo musical */

SP_COLUMNS ALBUNS;
GO

SELECT NOME AS "Album de Trap"
FROM ALBUNS 
WHERE ESTILO = 'Trap';
GO

/* Descobrir quantas músicas um determinado artista tem em cada álbum */

SELECT AR.NOME AS "Cantor",
       A.NOME AS "Album", 
	   COUNT(*) AS "Quantidade de Músicas"
FROM ARTISTAS AR
	INNER JOIN ARTISTAS_MUSICAS AM
	ON AM.id_ARTISTA = AR.idARTISTA
	INNER JOIN MUSICAS M
	ON AM.id_MUSICA = M.idMUSICA
	INNER JOIN ALBUNS A
	ON M.id_ALBUM = A.idALBUM
GROUP BY AR.NOME,A.NOME;

/* Encontrar todos os artistas que lançaram álbuns em uma determinada data */

/* LANÇARAM ALBUM EM 2020 */

SELECT TOP(1) AR.NOME AS "Cantor", 
              A.NOME AS "Album", 
			  DATA_LANCAMENTO AS "Data de Lançamento"
FROM ARTISTAS AR
	INNER JOIN ARTISTAS_MUSICAS AM
	ON AM.id_ARTISTA = AR.idARTISTA
	INNER JOIN MUSICAS M
	ON AM.id_MUSICA = M.idMUSICA
	INNER JOIN ALBUNS A
	ON M.id_ALBUM = A.idALBUM
WHERE DATA_LANCAMENTO LIKE '2020%'
;
GO

/* Listar todas as músicas de um determinado estilo musical */

SELECT M.NOME AS "Musica", A.NOME AS "Album", A.ESTILO AS "Estilo do Album"
FROM ALBUNS A
INNER JOIN MUSICAS M
ON M.id_ALBUM = A.idALBUM
WHERE A.ESTILO = 'Pop';






